apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app.kubernetes.io/name: python-app
  name: python-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: python-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: python-app
    spec:
      containers:
      - name: python-app
        image: docker.io/platun0v/devops-lab2:latest
        ports:
        - containerPort: 8000
        command: ['gunicorn']
        args: ['app.main:app', '-b', '0.0.0.0:8000']
