#!/usr/bin/env -S ANSIBLE_ROLES_PATH=roles ansible-playbook
---
- hosts: all
  become: true
  serial: 1
  force_handlers: true
  roles:
    - role: docker
      tags: docker
    - role: web_app
      tags: web_app
